name = "MediaDb"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE.md"
description = "MediaDb — theme for UiB's MediaDb."
homepage = "https://github.com/semafor/blank/"
tags = []
features = ["blog"]
min_version = 0.15

[author]
  name = "Vimux"
  homepage = "https://github.com/vimux"
